/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mamangava_jbugcheck_JBugCheck */

#ifndef _Included_com_mamangava_jbugcheck_JBugCheck
#define _Included_com_mamangava_jbugcheck_JBugCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mamangava_jbugcheck_JBugCheck
 * Method:    BugCheck
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mamangava_jbugcheck_JBugCheck_BugCheck
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
